[tools]
bun  = "latest"
node = "latest"

[[watch_files]]
patterns = ["src/**/*.ts"]
run      = "mise build"

[tasks.build]
run = "bun run bundle"

[tasks.dev]
run = "bun run dev"

[tasks.lint]
run = "bun run lint"
